name: bump_deps

on:
  schedule:
    - cron: 0 0 */3 * *
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  bump_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - run: |-
          pnpm update
          pnpm install --lockfile-only

      - run: |-
          rm -rf @types
          mkdir -p @types
          wget https://gitlab.com/novi028/JS-Slash-Runner/-/raw/main/dist/@types.zip -O @types.zip
          tar -xf @types.zip -C @types
          rm -f @types.zip

      - run: |-
          rm -f tavern_sync.mjs
          wget https://raw.githubusercontent.com/StageDog/tavern_sync/refs/heads/main/dist/tavern_sync.mjs

      - name: Check if only pnpm-lock.yaml is changed
        id: should_commit
        run: |-
          export changed_files=$(git diff --name-only HEAD | grep -v '^$')
          export num_changed_files=$(echo "$changed_files" | wc -l)
          if [ "$num_changed_files" -eq 1 ] && [ "$changed_files" = "pnpm-lock.yaml" ]; then
            echo "result=false" >> "$GITHUB_OUTPUT"
          else
            echo "result=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      - name: Commit if not only pnpm-lock.yaml is changed
        if: steps.should_commit.outputs.result == 'true'
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bump deps'
